const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const ProductSchema = new Schema({
  name: { type: String },
  company: { type: String },
  class: { type: String },
  releasedYear: { type: String },
  discountCode: { type: String },
  productLink: { type: String },
  youtubeReview: { type: String },
  discountedPrice: { type: String },
  shippingUSA: { type: String },
  shippingAustralia: { type: String },
  shippingUK: { type: String },
  height: { type: String },
  width: { type: String },
  weight: { type: String },
  cable: { type: String },
  pulsing: { type: String },
  modularSupport: { type: String },
  stands: { type: String },
  inbuiltTimer: { type: String },
  warranty: { type: String },
  returnsPolicy: { type: String },
  leds: { type: String },
  ledDualChip: { type: String },
  ledChipPower: { type: String },
  led480: { type: String },
  wavelengths610: { type: String },
  wavelengths630: { type: String },
  wavelengths660: { type: String },
  wavelengths810: { type: String },
  wavelengths830: { type: String },
  wavelengths850: { type: String },
  wavelengths930: { type: String },
  wavelengths950: { type: String },
  testedPeakWavelengths: { type: String },
  totalPowerOutput: { type: String },
  power9spots: { type: String },
  peakPowerCombined: { type: String },
  wattageDraw: { type: String },
  discountedPerLed: { type: String },
  discountedPerWatt: { type: String },
  EMFElectric3: { type: String },
  EMFElectric6: { type: String },
  magnetic3: { type: String },
  magnetic6: { type: String },
  micowave3: { type: String },
  micowave6: { type: String },
  flicker: { type: String },
  sound: { type: String },
  certificates: { type: String },
  dataValid: { type: String },
  date: {
    type: Date,
    default: Date.now
  }
});

module.exports = mongoose.model('product', ProductSchema);
